using System;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace DomainMembershipCheckRepair
{
    internal static class AdvancedSupportBundleService
    {
        internal static string Export(
            AdvancedDiagnosticsResult advanced,
            string outputPath,
            bool includeApplicationLog)
        {
            if (advanced == null)
                throw new ArgumentNullException("advanced");

            string path = outputPath;
            if (String.IsNullOrWhiteSpace(path))
                path = Path.Combine(
                    Environment.CurrentDirectory,
                    "DomainMembershipSupport-" + Environment.MachineName + "-" +
                    DateTime.Now.ToString("yyyyMMdd-HHmmss") + ".zip");

            path = Path.GetFullPath(path);
            string folder = Path.GetDirectoryName(path);
            if (!String.IsNullOrWhiteSpace(folder) && !Directory.Exists(folder))
                Directory.CreateDirectory(folder);

            string temp = Path.Combine(Path.GetTempPath(), "DomainMembershipCheckRepair", Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(temp);

            try
            {
                Write(Path.Combine(temp, "advanced-diagnostics.txt"), AdvancedDiagnosticsService.ToText(advanced));
                Write(Path.Combine(temp, "diagnostics.json"), DiagnosticsService.ToJson(advanced.Snapshot));
                Write(Path.Combine(temp, "netsetup-analysis.txt"), NetSetupLogAnalyzer.ToText(advanced.NetSetup));
                Write(Path.Combine(temp, "dns-diagnostics.txt"), DnsDiagnosticsService.ToText(advanced.Dns));
                Write(Path.Combine(temp, "dc-matrix.txt"), DcMatrixService.ToText(advanced.DcMatrix));
                Write(Path.Combine(temp, "event-timeline.txt"), EventTimelineService.ToText(advanced.Events));
                Write(Path.Combine(temp, "cyberark-epm.txt"), CyberArkDiagnosticsService.ToText(advanced.CyberArk));
                Write(Path.Combine(temp, "machine-password.txt"), MachinePasswordAnalyzer.ToText(advanced.MachinePassword));
                Write(Path.Combine(temp, "recovery-plan.txt"), RecoveryPlanService.ToText(advanced.RecoveryPlan));

                CollectCommand(temp, "ipconfig-all.txt", "ipconfig.exe", "/all");
                CollectCommand(temp, "route-print.txt", "route.exe", "print");
                CollectCommand(temp, "w32tm-status.txt", "w32tm.exe", "/query /status");
                CollectCommand(temp, "w32tm-source.txt", "w32tm.exe", "/query /source");

                string domain = advanced.Snapshot == null ? String.Empty : advanced.Snapshot.TargetDomain;
                if (!String.IsNullOrWhiteSpace(domain))
                {
                    CollectCommand(temp, "nltest-dsgetdc.txt", "nltest.exe", "/dsgetdc:" + domain);
                    CollectCommand(temp, "nltest-dclist.txt", "nltest.exe", "/dclist:" + domain);
                    CollectCommand(temp, "nltest-sc-query.txt", "nltest.exe", "/sc_query:" + domain);
                }

                if (File.Exists(DiagnosticsService.NetSetupLogPath))
                    Copy(DiagnosticsService.NetSetupLogPath, Path.Combine(temp, "NetSetup.log"));
                if (includeApplicationLog && File.Exists(DiagnosticsService.ApplicationLogPath))
                    Copy(DiagnosticsService.ApplicationLogPath, Path.Combine(temp, "DomainMembershipRepair.log"));

                Write(
                    Path.Combine(temp, "README.txt"),
                    "Advanced support bundle generated by DomainMembershipCheckRepair.\r\n" +
                    "Entered passwords are never written by the application.\r\n" +
                    "Windows logs and command output can contain environment-specific hostnames, domains, addresses, usernames, or other operational metadata. Review before sharing.\r\n");

                if (File.Exists(path))
                    File.Delete(path);
                ZipFile.CreateFromDirectory(temp, path, CompressionLevel.Optimal, false);
                return path;
            }
            finally
            {
                try { Directory.Delete(temp, true); } catch { }
            }
        }

        private static void CollectCommand(string folder, string name, string exe, string args)
        {
            CommandResult result = ProcessRunner.Run(exe, args, 10000);
            string output = result.CombinedOutput;

            if (result.TimedOut)
                output += Environment.NewLine + "[Command timed out]";
            if (!String.IsNullOrWhiteSpace(result.Error))
                output += Environment.NewLine + "[Runner error] " + result.Error;
            if (result.Started && !result.TimedOut)
                output += Environment.NewLine + "[Exit code] " + result.ExitCode;

            Write(Path.Combine(folder, name), output);
        }

        private static void Copy(string source, string destination)
        {
            try { File.Copy(source, destination, true); }
            catch (Exception ex) { Write(destination + ".copy-error.txt", ex.Message); }
        }

        private static void Write(string path, string text)
        {
            File.WriteAllText(path, text ?? String.Empty, new UTF8Encoding(false));
        }
    }
}
